// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPmBWhQ3XkVzp3Tu7hcCJq9MeuA3o1alw',
    appId: '1:591116589671:web:da4dcd1801ff8df59312c2',
    messagingSenderId: '591116589671',
    projectId: 'sweater-spark',
    authDomain: 'sweater-spark.firebaseapp.com',
    storageBucket: 'sweater-spark.firebasestorage.app',
    measurementId: 'G-E7CHCW6VKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVEYf9s-x3fA4eCdgOG-wbSD7zn1qRJgo',
    appId: '1:591116589671:android:4883f96da56546959312c2',
    messagingSenderId: '591116589671',
    projectId: 'sweater-spark',
    storageBucket: 'sweater-spark.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfbeK6SYDMQwiPEnPi2QVAKLaozzGd_h0',
    appId: '1:591116589671:ios:b81aa9a9e88e9ecf9312c2',
    messagingSenderId: '591116589671',
    projectId: 'sweater-spark',
    storageBucket: 'sweater-spark.firebasestorage.app',
    iosBundleId: 'com.example.sweater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfbeK6SYDMQwiPEnPi2QVAKLaozzGd_h0',
    appId: '1:591116589671:ios:b81aa9a9e88e9ecf9312c2',
    messagingSenderId: '591116589671',
    projectId: 'sweater-spark',
    storageBucket: 'sweater-spark.firebasestorage.app',
    iosBundleId: 'com.example.sweater',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPmBWhQ3XkVzp3Tu7hcCJq9MeuA3o1alw',
    appId: '1:591116589671:web:fc3140eeda0882c49312c2',
    messagingSenderId: '591116589671',
    projectId: 'sweater-spark',
    authDomain: 'sweater-spark.firebaseapp.com',
    storageBucket: 'sweater-spark.firebasestorage.app',
    measurementId: 'G-W1JMX05253',
  );

}